# Netlify Configuration voor Missie Weerbaarheid

[build]
  publish = "."
  
# Email notificaties voor contact form
[[notifications]]
  type = "email"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
